# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Conrad Lusk
title: Software Developer
email: luskconrad@gmail.com
website: www.github.com/sudo-sandwich

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  sudo-sandwich
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Conrad and I'm a software developer, with a primary interest in game development. I am currently a student. I taught myself almost everything I know about computer science well before I began college, starting with Game Maker 7 when I was in elementary school.

  I have worked with several Minecraft Marketplace creators as the primary dev on multiple projects, where I learned leadership and communication skills. During my time working on Minecraft Marketplace content I developed a C# library that automates much of the workload, which is still in active development today.

  **Technical Skills**
  - C# (4 years)
  - Java (2 years)
  - Python (2 years)
  - Lua (1 year)
  - Unity (2 years)
  - AWS (1 year)
  - Git (7 years)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Bedrock.NET
        link: https://github.com/sudo-sandwich/Bedrock.NET
        # link_text: Project Website
        # additional_links:
          # - title:  Bedrock.NET
            # icon: fab fa-github
            # url: https://github.com/sudo-sandwich/Bedrock.NET
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Automate many aspects of Minecraft addon creation.
        description: | # this will include new lines to allow paragraphs
          I started this project during a fit of rage while learning how to create Minecraft addons. A lot of the design decisions made for Bedrock's component based system are somewhat irritating to work with, which prompted me to create this library so I wouldn't have to deal with it. Most of my Minecraft development happens with Bedrock.NET and it has grown to a point where multiple developers and studios are using it. There have been 5 projects released on the marketplace either fully or partially developed using Bedrock.NET, with several more nearing the end of development.
      - layout: top-middle
        title: BSP Dungeon Generator
        link: https://github.com/sudo-sandwich/BSPDungeonGenerator
        quote: >
          Generate a 2d dungeon using binary space partitioning!
        description: |
          A unity project that generates a very simple 2d dungeon using binary space partitioning to determine the room layout.
      - layout: top-middle
        title: Lacks Skill
        link: https://github.com/sudo-sandwich/Lacks-Skill
        quote: >
          Kick unprepared players from your One Down Death Sentence Payday 2 lobby.
        description: |
          If you've ever played Payday 2 on the highest difficulty you know it's not for the faint of heart. There are a couple skills on the skill tree that are an absolute requirement and new players will sometimes join high difficulty lobbies without realizing what they've signed themselves up for. This mod quickly checks the skill tree of any player that joins and kicks players who are missing certain skills.
      - layout: top-middle
        title: RGBLighting
        link: https://github.com/sudo-sandwich/RGBLighting
        quote: >
          Synchronize RGB effects for G.Skill TridentZ RAM and Corsair Lighting Node Pro.
        description: |
          Since every computer hardware brand wants to have their own RGB software, if you get parts from two different brands you can't really synchronize the lighting effects. Well, since I had G.Skill TridentZ RAM and a Corsair Lighting Node Pro I wrote some software that would leverage the APIs of both brands to create a unified effect. Problem was Asus's API used C# while Corsair's API used C++, so I wound up writing some unmanaged code in a managed language. Learned my lesson about trying that.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shapescape
        link: https://shapescape.com/
        # link_text: boringcompany.com
        sub_title: Gameplay Developer
        caption: September 2019 - March 2021
        quote: >
          Creating Minecraft Marketplace content for a large Minecraft Partner.
        description: | # this will include new lines to allow paragraphs
          Shapescape is one of the larger Minecraft Partners, with several branches dedicated to level design, gameplay, post production, etc.. When I started at Shapescape I actually knew next to nothing about minecraft development. I quickly picked it up and began writing Bedrock.NET on the side because of my frustrations with Minecraft. Eventually, I was the lead dev on Craftable Furniture, Shapescape's highest grossing addon at the time.
      
          - Worked as the sole developer on most projects.
          - Collaborated with model makers, texture artists, sound designers, and other non-devs.
          - Learned how to work with undocumented systems.
          - Developed and documented tools to automate tasks for other developers, most of which are still in use.
      - layout: left
        title: Starfish Studios
        link: https://twitter.com/starfishstudios
        sub_title: Gameplay Developer
        caption: December 2020 - present
        quote: >
          Creating Minecraft Marketplace content for a small Minecraft Partner.
        description: |
          Starfish Studios is a much smaller company than Shapescape, which presented me with a set of challenges I had not yet experienced at Shapescape. 

          - Participated in the iterative design process of most addons.
          - Merged multiple projects into a single, unified product.
          - Set up Gitlab for the entire company.

      - layout: left
        title: Tsunami Studios
        sub_title: Gameplay Developer
        caption: February 2021 - present
        quote: >
          Creating Minecraft Marketplace content for a tiny Minecraft Partner.
        description: |
          A friend of mine wanted to try his hand at the Minecraft Marketplace so I am currently his sole dev. He is doing the level design, I am doing the gameplay design, and we have a modeller doing everything else.

          - Discussed design and scope before projects even started.
          - Coordinated required resources for projects.
          - Interviewed possible new hires for the company.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of North Carolina at Charlotte
        caption: 2018 - present (2023)
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
          I've been breezing through all of my computer science classes because I've already taught myself most of the material in class, but in my other classes I have learned how to manage deadlines, perfection vs expediency, and teamwork. During my sophmore year I had to withdraw due to medical circumstances, but I have since returned. Thankfully, the only result of the withdrawal was graduating a year later than I would have otherwise.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I'm primarily a coder and a gamer. Most of my time is spent doing one of those two things. I like pretty much all genres of games and I have played a *lot* of different games. My other interests include:
      - Frisbee golf
      - Camping
      - Biking
      - Hiking

      Me and a friend at the Breakaway Music Festival.
      ![Breakaway Music Festival](/images/breakaway.jpg "Breakaway Music Festival")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
